In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
forest_file = "../data/Bird_Monitoring_Data_FOREST.xlsx"

forest_excel = pd.ExcelFile(forest_file)

forest_sheet_names = forest_excel.sheet_names

print("Forest Sheets:")
print(forest_sheet_names)
print(f"\nTotal Sheets: {len(forest_sheet_names)}")

Forest Sheets:
['ANTI', 'CATO', 'CHOH', 'GWMP', 'HAFE', 'MANA', 'MONO', 'NACE', 'PRWI', 'ROCR', 'WOTR']

Total Sheets: 11

In [3]:
forest_sheets_dict = {
    sheet: forest_excel.parse(sheet)
    for sheet in forest_sheet_names
}

forest_df = pd.concat(
    [
        df.assign(Admin_Sheet=sheet_name)
        for sheet_name, df in forest_sheets_dict.items()
    ],
    ignore_index=True
)

forest_df.head()

,Admin_Unit_Code,Sub_Unit_Code,Site_Name,Plot_Name,Location_Type,Year,Date,Start_Time,End_Time,Observer,Visit,Interval_Length,ID_Method,Distance,Flyover_Observed,Sex,Common_Name,Scientific_Name,AcceptedTSN,NPSTaxonCode,AOU_Code,PIF_Watchlist_Status,Regional_Stewardship_Status,Temperature,Humidity,Sky,Wind,Disturbance,Initial_Three_Min_Cnt,Admin_Sheet
0,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,1,0-2.5 min,Singing,<= 50 Meters,False,Undetermined,Eastern Towhee,Pipilo erythrophthalmus,179276.0,83803,EATO,False,True,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,True,ANTI
1,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,1,0-2.5 min,Calling,<= 50 Meters,False,NaN,White-breasted Nuthatch,Sitta carolinensis,178775.0,90935,WBNU,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,True,ANTI
2,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,1,2.5 - 5 min,Calling,50 - 100 Meters,False,NaN,Red-bellied Woodpecker,Melanerpes carolinus,178195.0,84865,RBWO,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,False,ANTI
3,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,1,2.5 - 5 min,Singing,<= 50 Meters,False,NaN,Orchard Oriole,Icterus spurius,179064.0,93634,OROR,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,False,ANTI
4,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,1,2.5 - 5 min,Visualization,<= 50 Meters,False,NaN,Northern Mockingbird,Mimus polyglottos,178620.0,88394,NOMO,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,False,ANTI

In [4]:
print("Forest Shape:")
print(forest_df.shape)

Forest Shape:
(8546, 30)

In [5]:
grassland_file = "../data/Bird_Monitoring_Data_GRASSLAND.xlsx"

grassland_excel = pd.ExcelFile(grassland_file)

grassland_sheet_names = grassland_excel.sheet_names

print("Grassland Sheets:")
print(grassland_sheet_names)
print(f"\nTotal Sheets: {len(grassland_sheet_names)}")

Grassland Sheets:
['ANTI', 'CATO', 'CHOH', 'GWMP', 'HAFE', 'MANA', 'MONO', 'NACE', 'PRWI', 'ROCR', 'WOTR']

Total Sheets: 11

In [6]:
grassland_sheets_dict = {
    sheet: grassland_excel.parse(sheet)
    for sheet in grassland_sheet_names
}

grassland_df = pd.concat(
    [
        df.assign(Admin_Sheet=sheet_name)
        for sheet_name, df in grassland_sheets_dict.items()
    ],
    ignore_index=True
)

grassland_df.head()

,Admin_Unit_Code,Sub_Unit_Code,Plot_Name,Location_Type,Year,Date,Start_Time,End_Time,Observer,Visit,Interval_Length,ID_Method,Distance,Flyover_Observed,Sex,Common_Name,Scientific_Name,AcceptedTSN,TaxonCode,AOU_Code,PIF_Watchlist_Status,Regional_Stewardship_Status,Temperature,Humidity,Sky,Wind,Disturbance,Previously_Obs,Initial_Three_Min_Cnt,Admin_Sheet
0,ANTI,NaN,ANTI-0054,Grassland,2018,2018-05-22 00:00:00,05:35:00,05:45:00,Elizabeth Oswald,1,0-2.5 min,Singing,50 - 100 Meters,False,Male,Chipping Sparrow,Spizella passerina,179435.0,84781.0,CHSP,False,False,20.0,79.0,Cloudy/Overcast,Light breeze (4-7 mph) wind felt on face,Slight effect on count,False,True,ANTI
1,ANTI,NaN,ANTI-0054,Grassland,2018,2018-05-22 00:00:00,05:35:00,05:45:00,Elizabeth Oswald,1,7.5 - 10 min,Singing,50 - 100 Meters,False,Undetermined,Eastern Bluebird,Sialia sialis,179801.0,87184.0,EABL,False,False,20.0,79.0,Cloudy/Overcast,Light breeze (4-7 mph) wind felt on face,Slight effect on count,False,False,ANTI
2,ANTI,NaN,ANTI-0054,Grassland,2018,2018-05-22 00:00:00,05:35:00,05:45:00,Elizabeth Oswald,1,0-2.5 min,Singing,<= 50 Meters,False,Male,Grasshopper Sparrow,Ammodramus savannarum,179333.0,83867.0,GRSP,False,False,20.0,79.0,Cloudy/Overcast,Light breeze (4-7 mph) wind felt on face,Slight effect on count,False,True,ANTI
3,ANTI,NaN,ANTI-0054,Grassland,2018,2018-05-22 00:00:00,05:35:00,05:45:00,Elizabeth Oswald,1,0-2.5 min,Singing,50 - 100 Meters,False,Undetermined,Eastern Bluebird,Sialia sialis,179801.0,87184.0,EABL,False,False,20.0,79.0,Cloudy/Overcast,Light breeze (4-7 mph) wind felt on face,Slight effect on count,False,True,ANTI
4,ANTI,NaN,ANTI-0054,Grassland,2018,2018-05-22 00:00:00,05:35:00,05:45:00,Elizabeth Oswald,1,0-2.5 min,Singing,50 - 100 Meters,False,Male,Field Sparrow,Spizella pusilla,179443.0,84790.0,FISP,False,True,20.0,79.0,Cloudy/Overcast,Light breeze (4-7 mph) wind felt on face,Slight effect on count,False,True,ANTI

In [7]:
print("Grassland Shape:")
print(grassland_df.shape)

Grassland Shape:
(8531, 30)

In [8]:
print("="*50)
print("FOREST DATASET")
print("="*50)

print("Shape :", forest_df.shape)

print("\nColumns:")
print(forest_df.columns.tolist())

print("\nData Types:")
print(forest_df.dtypes)

==================================================
FOREST DATASET
==================================================
Shape : (8546, 30)

Columns:
['Admin_Unit_Code', 'Sub_Unit_Code', 'Site_Name', 'Plot_Name', 'Location_Type', 'Year', 'Date', 'Start_Time', 'End_Time', 'Observer', 'Visit', 'Interval_Length', 'ID_Method', 'Distance', 'Flyover_Observed', 'Sex', 'Common_Name', 'Scientific_Name', 'AcceptedTSN', 'NPSTaxonCode', 'AOU_Code', 'PIF_Watchlist_Status', 'Regional_Stewardship_Status', 'Temperature', 'Humidity', 'Sky', 'Wind', 'Disturbance', 'Initial_Three_Min_Cnt', 'Admin_Sheet']

Data Types:
Admin_Unit_Code                           str
Sub_Unit_Code                          object
Site_Name                                 str
Plot_Name                                 str
Location_Type                             str
Year                                    int64
Date                           datetime64[us]
Start_Time                             object
End_Time                               object
Observer                                  str
Visit                                   int64
Interval_Length                           str
ID_Method                                 str
Distance                                  str
Flyover_Observed                         bool
Sex                                       str
Common_Name                               str
Scientific_Name                           str
AcceptedTSN                           float64
NPSTaxonCode                            int64
AOU_Code                                  str
PIF_Watchlist_Status                     bool
Regional_Stewardship_Status              bool
Temperature                           float64
Humidity                              float64
Sky                                       str
Wind                                      str
Disturbance                               str
Initial_Three_Min_Cnt                    bool
Admin_Sheet                               str
dtype: object

In [9]:
print("="*50)
print("GRASSLAND DATASET")
print("="*50)

print("Shape :", grassland_df.shape)

print("\nColumns:")
print(grassland_df.columns.tolist())

print("\nData Types:")
print(grassland_df.dtypes)

==================================================
GRASSLAND DATASET
==================================================
Shape : (8531, 30)

Columns:
['Admin_Unit_Code', 'Sub_Unit_Code', 'Plot_Name', 'Location_Type', 'Year', 'Date', 'Start_Time', 'End_Time', 'Observer', 'Visit', 'Interval_Length', 'ID_Method', 'Distance', 'Flyover_Observed', 'Sex', 'Common_Name', 'Scientific_Name', 'AcceptedTSN', 'TaxonCode', 'AOU_Code', 'PIF_Watchlist_Status', 'Regional_Stewardship_Status', 'Temperature', 'Humidity', 'Sky', 'Wind', 'Disturbance', 'Previously_Obs', 'Initial_Three_Min_Cnt', 'Admin_Sheet']

Data Types:
Admin_Unit_Code                object
Sub_Unit_Code                  object
Plot_Name                      object
Location_Type                  object
Year                           object
Date                           object
Start_Time                     object
End_Time                       object
Observer                       object
Visit                          object
Interval_Length                object
ID_Method                      object
Distance                       object
Flyover_Observed               object
Sex                            object
Common_Name                    object
Scientific_Name                object
AcceptedTSN                    object
TaxonCode                      object
AOU_Code                       object
PIF_Watchlist_Status           object
Regional_Stewardship_Status    object
Temperature                    object
Humidity                       object
Sky                            object
Wind                           object
Disturbance                    object
Previously_Obs                 object
Initial_Three_Min_Cnt          object
Admin_Sheet                       str
dtype: object

In [10]:
forest_df.to_csv(
    "../cleaned_data/forest_raw.csv",
    index=False
)

grassland_df.to_csv(
    "../cleaned_data/grassland_raw.csv",
    index=False
)

print("Files Saved Successfully")

Files Saved Successfully